[workspace]
members = [
    "src/nr/x402_private_payment_router_contract",
    #"src/nr/token_contract"
]

[benchmark]
x402_private_payment_router_contract = "benchmarks/x402_private_payment_router_contract.benchmark.ts"
token = "benchmarks/token_contract.benchmark.ts"
#counter = "benchmarks/counter.benchmark.ts"
